version: '2'
services:
  mqtt:
    image: synoniem/alpine-mosquitto-certbot
    networks:
      - backend-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 80:80
    environment:
      - DOMAIN=mqtt.example.org
      - EMAIL=info@example.org
    volumes:
      - ./mosquitto/conf/:/mosquitto/conf
      - ./mosquitto/log/:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
    container_name: mqtt
    restart: always
networks:
  backend-net:
    external:
      name: backend-net
