version: '2'
services:
  mqtt:
    image: bitrox/mqtt
    networks:
      - backend-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8116:80
    environment:
      - DOMAIN=mqtt.bitrox.io
      - EMAIL=proxy@bitrox.io
    volumes:
      - ./mosquitto/conf/:/mosquitto/conf
      - ./mosquitto/log/:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
      - ./scripts:/scripts
    container_name: mqtt
    restart: always
networks:
  backend-net:
    external:
      name: backend-net
